export {
  loadCombatSession,
  resolveEquippedWeapon,
  resolveGermanFighter,
  resolveMission,
  synchronizeSharedModeAfterToggle,
} from './combat-session';
export type {
  CombatSession,
  CombatSessionCreationGuard,
  CombatSessionInput,
  TerminalCommitOutcome,
} from './combat-session';
export {
  createCombatSimulation,
  createCombatSimulationRuntime,
  stepCombatSimulation,
  submitCombatCommand,
  advanceSimulationFrames,
  applyDebugCommand,
  beginEvacuation,
  buildEvacuationCountdownReadModel,
  evacuationCountdownDisplaySeconds,
  evacuationEnemyOpacity,
  FIXED_STEP_SECONDS,
  FIXED_STEPS_PER_SECOND,
  MAX_STEPS_PER_FRAME,
  EVACUATION_COUNTDOWN_STEPS,
  EXIT_CENTRE_STEPS,
} from './combat-simulation';
export type {
  CombatSimulationState,
  CombatSimulationInput,
  CombatSimulationRuntime,
  CombatAircraftState,
  CombatBounds,
  CombatBoundsSize,
  CombatPoint,
  EvacuationCountdownReadModel,
  SimulationFrameResult,
} from './combat-simulation';
export {
  combatLifecycleReducer,
  evacuationAvailability,
  IDLE_COMBAT_LIFECYCLE,
  RUNNING_COMBAT_LIFECYCLE,
} from './lifecycle';
export type {
  CombatLifecycleAction,
  CombatLifecycleState,
  CombatOverlayId,
  DebugRestoreOrigin,
  EvacuationAvailability,
  EvacuationConfirmationOrigin,
} from './lifecycle';
export {
  EVIDENCE_MODE,
  EVIDENCE_SCENARIOS_ENABLED,
  EVIDENCE_COUNTERS_ENABLED,
  createCollisionEvidenceSink,
  createCombatEvidenceAccumulator,
} from './evidence';
export type {
  CollisionEvidenceSink,
  CollisionWorkTotals,
  CombatEvidenceAccumulator,
  CombatEvidenceRecord,
  CombatEvidenceWindow,
  LegacyBenchmarkIdentityWindow,
} from './evidence';
export {
  buildCombatObservability,
  isDebugCommandEligible,
} from './debug-command';
export type {
  CombatDebugCommand,
  CombatDebugHullValue,
  CombatObservability,
  DebugEligibilityContext,
} from './debug-command';
export {
  advanceEliteCannonProjectile,
  advanceEliteHomingCore,
  advanceEnemyProjectile,
  advanceProjectile,
  eliteCannonHeadingRadians,
  eliteCannonProjectileGeometry,
  eliteCannonSpeedPxPerSecond,
  eliteCoreProjectileGeometry,
  eliteCoreSpeedPxPerSecond,
  isEliteHomingCoreRemoved,
  isEnemyProjectileOutsideViewport,
  isProjectileOutsideViewport,
  isProjectileRemoved,
  projectileGeometry,
  projectileSpeedPxPerSecond,
  rangedProjectileGeometry,
  rangedProjectileSpeedPxPerSecond,
  resolveWeaponFireProfile,
  shortestHeadingTurnRadians,
  spawnEliteCannonProjectile,
  spawnEliteHomingCore,
  spawnProjectile,
  spawnRangedProjectile,
  stepsPerShotFor,
  ELITE_CANNON_DAMAGE,
  ELITE_CANNON_MUZZLE_X_FRACTION,
  ELITE_CANNON_MUZZLE_Y_FRACTION,
  ELITE_CANNON_PROJECTILE_HEIGHT_RATIO,
  ELITE_CANNON_PROJECTILE_WIDTH_RATIO,
  ELITE_CANNON_SPEED_VIEWPORT_HEIGHTS_PER_SECOND,
  ELITE_CANNON_TILT_RADIANS,
  ELITE_CORE_DAMAGE,
  ELITE_CORE_LIFETIME_STEPS,
  ELITE_CORE_MUZZLE_Y_FRACTION,
  ELITE_CORE_PROJECTILE_HEIGHT_RATIO,
  ELITE_CORE_PROJECTILE_WIDTH_RATIO,
  ELITE_CORE_SPEED_VIEWPORT_HEIGHTS_PER_SECOND,
  ELITE_CORE_TURN_RADIANS_PER_STEP,
  PROJECTILE_HEIGHT_RATIO,
  PROJECTILE_WIDTH_RATIO,
  RANGED_PROJECTILE_DAMAGE,
  RANGED_PROJECTILE_HEIGHT_RATIO,
  RANGED_PROJECTILE_SPEED_VIEWPORT_HEIGHTS_PER_SECOND,
  RANGED_PROJECTILE_WIDTH_RATIO,
} from './projectiles';
export type {
  CombatProjectile,
  EliteCannonProjectile,
  EliteHomingCore,
  EnemyProjectile,
  EnemyProjectileInstance,
  ProjectileBounds,
  ProjectileGeometry,
  WeaponFireProfile,
} from './projectiles';
export {
  activateElite,
  createEliteAtAnchor,
  createEliteForEntry,
  drawEliteMovementDecision,
  eliteAcceptsProjectileDamage,
  isEliteContactActive,
  isEliteProjectileTargetEligible,
  isEnemyAnyPortionVisible,
  isEnemyFullyInsideViewport,
  isEnemyFullyOutsideViewport,
  reprojectEliteForViewport,
  spawnEnemyFromPlacement,
  stepEnemy,
  ELITE_ANCHOR_VIEWPORT_FRACTION_X,
  ELITE_ANCHOR_VIEWPORT_FRACTION_Y,
  ELITE_ARMOURED_PHASE_STEPS,
  ELITE_CANNON_INTERVAL_STEPS,
  ELITE_CORE_INTERVAL_STEPS,
  ELITE_ENTRY_SPEED_VIEWPORT_HEIGHT_PER_SECOND,
  ELITE_HORIZONTAL_SPEED_VIEWPORT_WIDTH_PER_SECOND,
  ELITE_MOVEMENT_INTERVAL_DRAW_RANGE,
  ELITE_MOVEMENT_MIN_INTERVAL_STEPS,
  ELITE_PHASE_CYCLE_STEPS,
  ELITE_VULNERABLE_PHASE_STEPS,
} from './enemies';
export type {
  BasicEnemyState,
  CombatEnemy,
  EliteCreationInput,
  EliteEnemyState,
  EliteMovementDecision,
  ElitePhase,
  EnemyEntryRegion,
  EnemyStepInput,
  EnemyStepResult,
  HunterEnemyState,
  RangedEnemyState,
} from './enemies';
export {
  aircraftCollisionAabb,
  enemyCollisionAabb,
  enemyProjectileCollisionAabb,
  projectileCollisionAabb,
  AIRCRAFT_HITBOX_HEIGHT_RATIO,
  AIRCRAFT_HITBOX_WIDTH_RATIO,
} from './collision-geometry';
export {
  resolveAircraftContacts,
  resolveEnemyProjectileCollisions,
  resolveProjectileCollisions,
  AIRCRAFT_DAMAGE_FLASH_STEPS,
  DESTROYED_ENEMY_FLASH_STEPS,
  ELITE_CONTACT_DAMAGE,
  ENEMY_HIT_FLASH_STEPS,
  PAIR_CONTACT_COOLDOWN_STEPS,
} from './collision';
export type {
  ContactCollisionInput,
  ContactCollisionResult,
  DestroyedEnemyFlash,
  DestroyedEnemyInfo,
  EliteDeflectionFeedback,
  EliteDeflectionFeedbacks,
  EnemyProjectileCollisionInput,
  EnemyProjectileCollisionResult,
  ProjectileCollisionInput,
  ProjectileCollisionResult,
} from './collision';
export {
  resolveMovementConfig,
  brakingDistance,
  MOVEMENT_RATIOS,
  MOVEMENT_TIMING_SECONDS,
} from './movement-config';
export type { MovementConfig } from './movement-config';
export { isPointerInsideViewport } from './input-command';
export {
  routeKeyInput,
  shouldForwardPointerMove,
  KEY_BINDING_TABLE,
} from './input-routing';
export type {
  CombatInputContext,
  CombatKeyBinding,
  RoutedKeyIntent,
} from './input-routing';
export type {
  CombatInputCommand,
  CombatControlMode,
  CombatMovementKey,
} from './input-command';
